# Generated by Django 3.2.7 on 2021-10-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211010_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='location',
            field=models.JSONField(null=True),
        ),
    ]
