# Generated by Django 3.2.7 on 2021-10-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_problem_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='location',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
