# Generated by Django 3.2.7 on 2021-10-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_problem_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
