# Generated by Django 3.2.7 on 2021-10-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_problem_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='summary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
