# Generated by Django 3.2.7 on 2021-10-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_problem_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_resolved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
