# Generated by Django 3.2.7 on 2021-10-09 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='downvote_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='picture_url',
            field=models.TextField(blank=True, default='https://i1.wp.com/leanprojectplaybook.com/wp-content/uploads/2017/07/Problem-Solution-Fit-64922822_xxl-Puzzle-Piece-e1499237044963.jpg?resize=1030%2C438'),
        ),
        migrations.AddField(
            model_name='problem',
            name='severity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='upvote_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
